// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF_for_bokstore.Models;

#nullable disable

namespace WPF_for_bokstore.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksAuthor", b =>
                {
                    b.Property<string>("BooksIsbn13")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("BooksISBN13");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BooksIsbn13", "AuthorId")
                        .HasName("PK__BooksAut__B3586DCC5303EBB0");

                    b.HasIndex("AuthorId");

                    b.ToTable("BooksAuthor", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Efternamn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Födelsedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Book", b =>
                {
                    b.Property<string>("Isbn13")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("ISBN13");

                    b.Property<int?>("BookFormatId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("Release_Date");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Isbn13")
                        .HasName("PK__Books__3BF79E031FF9534D");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.BookFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FormatName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__BookForm__3214EC07141D5944");

                    b.ToTable("BookFormat", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC07F38A3B51");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Genre__3214EC076A7DD8DD");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipVia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Order__3214EC0714614790");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookIsbn13")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("BookISBN13");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC0747B0B598");

                    b.HasIndex("BookIsbn13");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Publishe__3214EC07AF2CCC02");

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.StockBalance", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("StoreID");

                    b.Property<string>("BookIsbn13")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("BookISBN13");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "BookIsbn13")
                        .HasName("Stock");

                    b.HasIndex("BookIsbn13");

                    b.ToTable("StockBalance", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.StockBalanceBygenrePublisherInStore", b =>
                {
                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GenreName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StockBalance")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable((string)null);

                    b.ToView("StockBalanceBYGenrePublisherInStore", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Store__3214EC07C9A4D427");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.TitlePerAuthor", b =>
                {
                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<decimal?>("StockValue")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<int?>("Titles")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("TitlePerAuthor", (string)null);
                });

            modelBuilder.Entity("BooksAuthor", b =>
                {
                    b.HasOne("WPF_for_bokstore.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__BooksAuth__Autho__5535A963");

                    b.HasOne("WPF_for_bokstore.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksIsbn13")
                        .IsRequired()
                        .HasConstraintName("FK__BooksAuth__Books__6477ECF3");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Book", b =>
                {
                    b.HasOne("WPF_for_bokstore.Models.BookFormat", "BookFormat")
                        .WithMany("Books")
                        .HasForeignKey("BookFormatId")
                        .HasConstraintName("Fk_BookFormatId");

                    b.HasOne("WPF_for_bokstore.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK__Books__GenreId__48CFD27E");

                    b.HasOne("WPF_for_bokstore.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK__Books__Publisher__628FA481");

                    b.Navigation("BookFormat");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Order", b =>
                {
                    b.HasOne("WPF_for_bokstore.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Order_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.OrderDetail", b =>
                {
                    b.HasOne("WPF_for_bokstore.Models.Book", "BookIsbn13Navigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BookIsbn13")
                        .HasConstraintName("FK__OrderDeta__BookI__03F0984C");

                    b.HasOne("WPF_for_bokstore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__02FC7413");

                    b.Navigation("BookIsbn13Navigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.StockBalance", b =>
                {
                    b.HasOne("WPF_for_bokstore.Models.Book", "BookIsbn13Navigation")
                        .WithMany("StockBalances")
                        .HasForeignKey("BookIsbn13")
                        .IsRequired()
                        .HasConstraintName("FK_ISBN_Books");

                    b.HasOne("WPF_for_bokstore.Models.Store", "Store")
                        .WithMany("StockBalances")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__StockBala__Store__5629CD9C");

                    b.Navigation("BookIsbn13Navigation");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Book", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.BookFormat", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WPF_for_bokstore.Models.Store", b =>
                {
                    b.Navigation("StockBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
